name: Scheduled News Ingestion

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch: 

jobs:
  ping-api:
    runs-on: ubuntu-latest 

    steps:
      - name: Trigger Live EC2 API
        run: |
          curl -X POST https://pulse.adityagaur.me/api/ingest/trigger